# See docs.getsentry.com/on-premise/server for instructions

version: '2'
services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - ./data:/var/lib/sentry/files

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.0-alpine

  postgres:
    image: postgres:9.5

  web:
    extends: base
    links:
      - redis
      - postgres
      - memcached
    ports:
      - '9000:9000'

  cron:
    extends: base
    command: celery beat
    links:
      - redis
      - postgres
      - memcached

  worker:
    extends: base
    command: celery worker
    links:
      - redis
      - postgres
      - memcached
